<a href="https://colab.research.google.com/github/greyhound101/IEEE-CIS-Fraud/blob/master/finding_magic_feature_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.environ['KAGGLE_USERNAME'] = "tapaskd123" # username from the json file
os.environ['KAGGLE_KEY'] = "aba8dc1f085221111d925003fe5a88ed" # key from the json file
!kaggle competitions download -c ieee-fraud-detection

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)
test_identity.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
test_transaction.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_transaction.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_identity.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Mounted at /content/gdrive

In [ ]:
import pandas as pd
import numpy as np
trn=pd.read_csv('train_transaction.csv.zip')
tst=pd.read_csv('test_transaction.csv.zip')
trn_idn=pd.read_csv('train_identity.csv.zip')

In [ ]:
trn=trn.merge(trn_idn,on='TransactionID',how='left')
import gc
del([trn_idn])
gc.collect()

413

In [ ]:
trn.head()

   TransactionID  isFraud  ...  DeviceType                     DeviceInfo
0        2987000        0  ...         NaN                            NaN
1        2987001        0  ...         NaN                            NaN
2        2987002        0  ...         NaN                            NaN
3        2987003        0  ...         NaN                            NaN
4        2987004        0  ...      mobile  SAMSUNG SM-G892A Build/NRD90M

[5 rows x 434 columns]

In [ ]:
trn['day']=trn['TransactionDT']//86400
for col in range(1,16):
  trn['d_'+str(col)]=trn['day']-trn['D'+str(col)]

In [ ]:
print(trn.shape,tst.shape)

(590540, 450) (506691, 393)

In [ ]:
def second(data):
  return data[data.find('.'):]
def first(data):
  return data[:data.find('.')]
trn['P_emaildomain'].fillna('nan',inplace=True)
trn['R_emaildomain'].fillna('nan',inplace=True)
trn['P_emaildomain_first']=trn['P_emaildomain'].apply(first)
trn['P_emaildomain_second']=trn['P_emaildomain'].apply(second)
trn['R_emaildomain_first']=trn['R_emaildomain'].apply(first)
trn['R_emaildomain_second']=trn['R_emaildomain'].apply(second)

In [ ]:
trn=trn.drop(['TransactionID','TransactionDT','isFraud'],1)
cat=list(trn.select_dtypes(include=object))
trn[cat]=trn[cat].fillna('nan')
trn=trn.fillna(-999)

In [ ]:
trn=trn.loc[trn['D1']<trn['day']].reset_index(drop=True)

In [ ]:
from tqdm import tqdm
def group(df,cols):
  df['id']=''
  for col in cols:
    df['id']+=df[col].astype(str)
  result=0
  for _,sdo in df.groupby(['id']):
    tmp=0
    tmp+=sdo['TransactionAmt'].values.sum()
    tmp-=sdo.tail(1)['V307'].values
    if tmp>0:
      result+=tmp
    else:
      tmp-=result
  return result
trn=trn.loc[:1000]
cols=list(trn)
cols.remove('TransactionAmt')
cols.remove('V307')
ans=0
ls=[]
dk={}
for col in tqdm(cols):
  ls.append(col)
  n_ans=group(trn,ls)
  dk[col]=n_ans
  if ans!=0:
    if n_ans>ans:
      ls.remove(col)
    else:
      ans=n_ans
  else:
    ans=n_ans

 36%|███▋      | 39/107 [1:19:36<3:54:43, 207.10s/it]

In [ ]:
ans

In [ ]:
dk

array([154888.81070376])

In [ ]:
ls

['ProductCD',
 'card1',
 'card3',
 'card4',
 'card5',
 'addr1',
 'addr2',
 'dist2',
 'P_emaildomain',
 'R_emaildomain',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C7',
 'C8',
 'C10',
 'C12',
 'D1',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D12',
 'D13',
 'D14',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'V29',
 'V30',
 'V31',
 'V32',
 'V33',
 'V34',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V138',
 'V141',
 'V142',
 'V143',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V169',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V220',
 'V223',
 'V224',
 'V225',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V302',
 'V303',
 'V304',
 'V305',
 'V325',
 'V326',
 'V327',
 'V334',
 'V335',
 'V336',
 'id_01',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_07',
 'id_08',
 'id_09',
 'id_10',
 'id_11',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_18',
 'id_19',
 'id_20',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo',
 'day',
 'd_1',
 'd_6',
 'd_7',
 'd_8',
 'd_9',
 'd_10',
 'd_12',
 'd_13',
 'd_14',
 'P_emaildomain_first',
 'P_emaildomain_second',
 'R_emaildomain_first',
 'R_emaildomain_second',
 'id']